# Generated by Django 5.2.1 on 2026-05-12 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuttype",
            name="product",
        ),
        migrations.AddField(
            model_name="cuttype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cuttype",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cuttype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ProductCutType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cut_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.cuttype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cut_types",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "cut_type")},
            },
        ),
    ]
