# Generated by Django 5.2.1 on 2026-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("today", "Quick Delivery Today"),
                    ("scheduled", "Scheduled Pick-up"),
                ],
                default="today",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="receive_method",
            field=models.CharField(
                choices=[
                    ("home_delivery", "Home Delivery"),
                    ("receive_in_market", "Receive in Market"),
                ],
                default="home_delivery",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
