# Generated by Django 5.2.1 on 2026-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_remove_category_icon_category_image_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
