# Generated by Django 5.2.1 on 2026-05-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("terms-and-conditions", "Terms & Conditions"),
                            ("privacy-policy", "Privacy Policy"),
                            ("refund-policy", "Refund & Cancellation Policy"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Support markdown content for formatting"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Information"),
                            ("orders", "Ordering & Delivery"),
                            (
                                "payments",
                                "Payments & Installments (Stripe/Tabby/Tamara)",
                            ),
                            ("refunds", "Refunds & Cancellations"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which question is shown"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["category", "sort_order", "created_at"],
            },
        ),
    ]
