# Generated by Django 5.2.1 on 2026-05-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=255, null=True)),
                ("tagline", models.TextField(blank=True, null=True)),
                (
                    "call_to_action",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="banners/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
